### ISSUE TITLE
[Lifecycle] remove version hardcoding 

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-osm#101]
**Enhancement Description**
Support multiple versions in the OSM adapter.

**Related Challenges**
* Currently the OSM adapter only installs OSM v0.6.0. We need to be able to fetch binaries for the latest releases and use the latest OSM.
* Also, when reading binaries from `~/.meshery/bin` it expects them to be in the form `osm-v0.6.0`. This is a side effect of point one but should be kept in mind.

---
**Alternatives**
Using `docker cp $binPath meshery_meshery-osm_1:/root/.meshery/bin/osm-v0.6.0` for tricking the adapater to believe that the current binary is for osm-v0.6.0. Too hacky.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
A helm-based approach is ideal, yeah?

**Comment by dhruv0000** [comment]
Educate me, why Helm is better than oam CLI? I believe we are using cli in other adaptors like istio.

**Comment by DelusionalOptimist** [comment]
@dhruv0000 Maybe this: https://github.com/meshery/meshery-linkerd/issues/215#issuecomment-890349080

**Comment by leecalcote** [comment]
@dhruv0000 scripting cli has long been something I've hoped we can avoid; something @kumarabd and I have struggled to see eye-to-eye on. With helm's SDK and patterns, we can finally move away.

**Comment by leecalcote** [comment]
To answer your question, put simply: CLIs are not APIs.￼
