### ISSUE TITLE
Adapter Operations are thread unsafe

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery-osm#106]
Description
OSM Adapter operations are thread unsafe at the moment due its usage of meshery-adapter-library viper config provider.

Expected Behavior
Operations should be thread safe. This is achievable by replacing meshery-adapter-library config provider implementation with meshkit config provider implementation which share similar interfaces.

Contributor Resources
Refer Istio Adapter to see how config provider can be replaced

**Comment by sayantan1413** [comment]
@utkarsh-pro can you verify this issue? If yes then I would like to work on it.

**Comment by utkarsh-pro** [comment]
@sayantan1413 yep, this adapter also has the same issue.
