### ISSUE TITLE
[Docs] Fix celebration image link location

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-osm#154]
#### Current State
The link to the celebration image is broken:
<img width="994" alt="Screen Shot 2022-05-30 at 11 59 55 AM" src="https://user-images.githubusercontent.com/7570704/171035493-c645f838-dcd0-4b2f-b774-25d4e931b6e8.png">

See this PR as an example - https://github.com/meshery/meshery-osm/issues/153#issuecomment-1141349963

#### Desired State
The link to this image should be https://raw.githubusercontent.com/meshery/meshery-osm/master/.github/welcome/Layer5-celebration.png. This workflow needs updated with the proper link - https://github.com/meshery/meshery-osm/blob/master/.github/config.yml

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by kingebere** [comment]
I am interested in fixing this

**Comment by leecalcote** [comment]
Shazam! ⚡

**Comment by leecalcote** [comment]
Apologies, @kingebere. I missed your comment and in that time @PrajwalBorkar knocked out the issue with a PR. There's more where this comes from, though - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
