### ISSUE TITLE
[Readme] Consistently present Meshery logo 

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery-osm#185]
**Current Situation**
A brief description of what the current circumstance is.

As you see the current logo is quite big and is not consistent. 
**Desired Situation**
A brief description of the necessary action to take.

Make it consistent with github.com/meshery/meshery 's readme logo.
---
[Optional] **Alternatives**
A brief description of any alternative solutions or features you've considered.

[Optional] **Additional context**
Add any other context or screenshots about the chore or task here.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by gaurav879** [comment]
I would like to work on this @legendarykamal.

**Comment by legendarykamal** [comment]
yes @gaurav879 here you go 🚀
