### ISSUE TITLE
[Docs]Error Links in Readme

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshery-osm#245]
#### Current State
The layer5 communtiy welcome guide link is leading to wrong link
![image](https://github.com/meshery/meshery-osm/assets/59855919/8083557c-8e17-4f44-9f53-4d5f67132f42)

#### Desired State
it could be possible that the link is deleted or we can switch it with the [newcomer's guide](https://layer5.io/community/newcomers)

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Ghat0tkach** [comment]
In both the cases , i would like to work on this issue

**Comment by Ghat0tkach** [comment]
@Kevin-Usadadiya wish to work on this issue?

**Comment by Kevin-Usadadiya** [comment]
Yes I am

**Comment by Ghat0tkach** [comment]
> Yes I am

Okay ! Draft a PR please

**Comment by Kevin-Usadadiya** [comment]
where this error is actually generated, I am not able to find the docs

**Comment by Ghat0tkach** [comment]
> Yes I am
> 

It is in the readme file.

**Comment by Kevin-Usadadiya** [comment]
> > Yes I am
> 
> It is in the readme file.

In which repo

**Comment by Ghat0tkach** [comment]
> > > Yes I am

Apologies for the confusion @leecalcote referenced this and completed this issue 2 weeks ago , he probably forgot to mention this  .  Dont worry join [Slack](https://slack.meshery.io/) and introduce yourself , you will find a lot of issues for yourself or refer to [good-first-issues](https://github.com/layer5io/layer5/labels/good%20first%20issue)

**Comment by Kevin-Usadadiya** [comment]
I have already Join Slack Community.
